/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Player;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author jarod
 */
public class PantallaJuego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public PantallaJuego() {
        initComponents();
        this.setTitle("Tres en Línea");
        _init_();
    }
    
    //crea la matriz de botones, primero cree un JButton[][] más abajo donde están los atributos
    public void _init_() {
        //la matriz es de 3 x 3
        int x = 3, y = 3;
        
        this.btnMatriz = new JButton[y][x]; //instancio

        //indico el tipo diseño, es de red
        //el 3 y el 4 indican los espacios entre los botones
        pnlMatriz.setLayout(new GridLayout(y, x,3,4));
        //recorro la martiz
        for (int i = 0; i < y; i++) {
            for (int j = 0; j < x; j++) {
                
                btnMatriz[i][j] = new JButton();
                //asigno el color
                btnMatriz[i][j].setBackground(new Color(230,58,59));
                //dimensiones del boton
                btnMatriz[i][j].setPreferredSize(new Dimension(45,45));
                //tipo de letra y tamaño
                btnMatriz[i][j].setFont(new Font("Arial", Font.PLAIN, 40));
                //y la añado al pnl donde está el diseño de red
                pnlMatriz.add(btnMatriz[i][j]);
            }
        }

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMatriz = new javax.swing.JPanel();
        lblJug1 = new javax.swing.JLabel();
        lblJug1Points = new javax.swing.JLabel();
        lblJug2 = new javax.swing.JLabel();
        lblJug2Points = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        lblQuien = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 58, 54));

        pnlMatriz.setBackground(new java.awt.Color(230, 58, 59));
        pnlMatriz.setPreferredSize(new java.awt.Dimension(231, 231));

        javax.swing.GroupLayout pnlMatrizLayout = new javax.swing.GroupLayout(pnlMatriz);
        pnlMatriz.setLayout(pnlMatrizLayout);
        pnlMatrizLayout.setHorizontalGroup(
            pnlMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        pnlMatrizLayout.setVerticalGroup(
            pnlMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        lblJug1.setForeground(new java.awt.Color(254, 254, 254));
        lblJug1.setText("Jugador(a) 1 :");

        lblJug1Points.setForeground(new java.awt.Color(254, 254, 254));
        lblJug1Points.setText("0");

        lblJug2.setForeground(new java.awt.Color(254, 254, 254));
        lblJug2.setText("Jugador(a) 2 :");

        lblJug2Points.setForeground(new java.awt.Color(254, 254, 254));
        lblJug2Points.setText("0");

        lblTurno.setForeground(new java.awt.Color(254, 254, 254));
        lblTurno.setText("Turno de :");

        lblQuien.setForeground(new java.awt.Color(254, 254, 254));

        btnJugar.setText("Limpiar");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJug1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJug1Points, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJug2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(lblJug2Points, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQuien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJug1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJug1Points)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJug2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJug2Points)
                        .addGap(18, 18, 18)
                        .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQuien, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaJuego().setVisible(true);
            }
        });
    }
    
    //creado por mi
    //vean que lo gris no se puede cambiar
    public JButton[][] btnMatriz;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnJugar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblJug1;
    public javax.swing.JLabel lblJug1Points;
    public javax.swing.JLabel lblJug2;
    public javax.swing.JLabel lblJug2Points;
    public javax.swing.JLabel lblQuien;
    private javax.swing.JLabel lblTurno;
    public javax.swing.JPanel pnlMatriz;
    // End of variables declaration//GEN-END:variables

    
    /************************************************
     no son set NORMALES
     * solo los coloca en pantalla
     * no se están asignando a algun atributo
     */
    //asigna los nombres al label
    public void setNames(String name1, String name2) {
        this.lblJug1.setText(name1 + " :");
        this.lblJug2.setText(name2 + " :");
    }

    //limpia la matriz
    public void clearMatrix() {
        for (JButton[] row : btnMatriz) {
            for (JButton column : row){
                column.setText("");
            }
        }
    }

    //asigna los char a la matriz
    public void setMatrix(char[][] matrix) {
        for (int i = 0; i < matrix.length; i++) {
            for (int j = 0; j < matrix[i].length; j++) {
                this.btnMatriz[i][j].setText(Character.toString(matrix[i][j]));
            }
        }
    }

    //setea de quien es el turno
    public void setWho(String name) {
        this.lblQuien.setText(name);
    }

  
    //setea los puntos en pantalla
    public void setPoint(int points, int points0) {
        this.lblJug1Points.setText(Integer.toString(points));
        this.lblJug2Points.setText(Integer.toString(points0));
    }
}
